//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolsEntities : DbContext
    {
        public SchoolsEntities()
            : base("name=SchoolsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Form> Forms { get; set; }
        public DbSet<Parent> Parents { get; set; }
        public DbSet<Parish> Parishes { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentsParent> StudentsParents { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
        public DbSet<Village> Villages { get; set; }
    }
}
