//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public Parent()
        {
            this.StudentsParents = new HashSet<StudentsParent>();
        }
    
        public int ParentID { get; set; }
        public string PFirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string PLastName { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string WorkPhone { get; set; }
    
        public virtual ICollection<StudentsParent> StudentsParents { get; set; }
    }
}
