//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicSchoolManagement.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolsEntities : DbContext
    {
        public SchoolsEntities()
            : base("name=SchoolsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdministrativeStaff> AdministrativeStaffs { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassesSchedule> ClassesSchedules { get; set; }
        public virtual DbSet<Day> Days { get; set; }
        public virtual DbSet<Parent> Parents { get; set; }
        public virtual DbSet<Parish> Parishes { get; set; }
        public virtual DbSet<SchoolForm> SchoolForms { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<StudentClass> StudentClasses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentsParent> StudentsParents { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Village> Villages { get; set; }
    }
}
